# Generated by Django 4.2.5 on 2023-09-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userTeam', '0001_initial'),
        ('assignedTask', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='fkUserTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userTeam.userteam'),
        ),
    ]
