# Generated by Django 4.2.5 on 2023-09-25 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLeader', models.BooleanField()),
                ('isMember', models.BooleanField()),
                ('isCreator', models.BooleanField()),
                ('fkTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('fkUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
