# Generated by Django 4.2.5 on 2023-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('expiratioDate', models.DateField()),
                ('state', models.CharField(default='Pendiente', max_length=40)),
            ],
        ),
    ]
